/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WkPlayer {
    /**
    * The first name
    */
    'schedule': Array<Object>;
  }
  interface WkPlayerAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'schedule'?: Array<Object>;
  }

  interface WkProduct {
    'wkProperties': string;
  }
  interface WkProductAttributes extends StencilHTMLAttributes {
    'wkProperties'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WkPlayer': Components.WkPlayer;
    'WkProduct': Components.WkProduct;
  }

  interface StencilIntrinsicElements {
    'wk-player': Components.WkPlayerAttributes;
    'wk-ds-product': Components.WkProductAttributes;
  }


  interface HTMLWkPlayerElement extends Components.WkPlayer, HTMLStencilElement {}
  var HTMLWkPlayerElement: {
    prototype: HTMLWkPlayerElement;
    new (): HTMLWkPlayerElement;
  };

  interface HTMLWkProductElement extends Components.WkProduct, HTMLStencilElement {}
  var HTMLWkProductElement: {
    prototype: HTMLWkProductElement;
    new (): HTMLWkProductElement;
  };

  interface HTMLElementTagNameMap {
    'wk-player': HTMLWkPlayerElement
    'wk-ds-product': HTMLWkProductElement
  }

  interface ElementTagNameMap {
    'wk-player': HTMLWkPlayerElement;
    'wk-ds-product': HTMLWkProductElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
